dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: default
    commands:
      - gem install bundler -v 1.16.6
      - bundle install
      - bundle exec rspec


ci:
  builds:
    - name: tests
      build_target: default